### ISSUE TITLE
Improve Space CZ  Tracking

### ISSUE THREAD

**Issue by aussig** [aussig/BGS-Tally#148]
Currently we assume a win if the player logs a kill within 5 minutes of dropping at a CZ and we don't track any other side objectives.

- [ ] Track number of kills to determine a win. Upside: More accurate detection of an actual win where you are fighting alone or in a Team when always focus-firing. Downside: Won't detect a win when in a Team and attacking different targets.

    * Low win: 7-9 kills
    * Med win: 12-14 kills
    * High win: 22-25 kills

- [ ] Track capital ship kills. Will need to examine logs to see whether we get any indication of the kill for this.
- [ ] Track side objective kills:

    * Enemy Spec ops: Likely approach will be to detect target name `Alpha`, `Beta`, `Gamma`, `Delta` and subsequent kill.
    * Enemy Captains: Likely approach will be to detect target name, `Captain` and subsequent kill.
    * Enemy Propagandists: Likely approach will be to detect target name, `Propagandist` and subsequent kill.
    * Allied Spec ops / Captains / Correspondents: Unlikely to be able to detect the successful defense of these.
