### ISSUE TITLE
Space CZ Side Objective Tracking

### ISSUE THREAD

**Issue by aussig** [aussig/BGS-Tally#175]
### Discussed in https://github.com/aussig/BGS-Tally/discussions/151

- [x] Track capital ship kills: Can be tracked using `CapShipBond` event.  Just a single kill for the correct faction needs to be made: 
    ```
    { "timestamp":"2024-02-29T17:49:55Z", "event":"CapShipBond", "Reward":500000, "AwardingFaction":"The Sovereign Justice Collective", "VictimFaction":"Skiraragea Allied PLC" }
    ```
- [ ] Track side objective Enemy Spec Ops: Detect target name `$LUASC_Scenario_Warzone_NPC_SpecOps_A`, `$LUASC_Scenario_Warzone_NPC_SpecOps_B`, `$LUASC_Scenario_Warzone_NPC_SpecOps_G`, `$LUASC_Scenario_Warzone_NPC_SpecOps_D` and subsequent `FactionKillBond`s. All four kills, one of each type for the correct target faction must be made:
    ```
    { "timestamp":"2024-02-26T18:09:59Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"python", "ScanStage":3, "PilotName":"$LUASC_Scenario_Warzone_NPC_SpecOps_A;", "PilotName_Localised":"Spec Ops Wing Alpha", "PilotRank":"Elite", "ShieldHealth":68.832222, "HullHealth":100.000000, "Faction":"Skiraragea Allied PLC", "LegalStatus":"Lawless" }

    { "timestamp":"2024-02-26T18:12:59Z", "event":"FactionKillBond", "Reward":49496, "AwardingFaction":"The Sovereign Justice Collective", "VictimFaction":"Skiraragea Allied PLC" }
    ```

- [ ] Track side objective Enemy Captains: Detect target name, `$LUASC_Scenario_Warzone_NPC_WarzoneGeneral_Emp`, `$LUASC_Scenario_Warzone_NPC_WarzoneGeneral_Fed`, or `$LUASC_Scenario_Warzone_NPC_WarzoneGeneral_Ind` and subsequent `FactionKillBond`. Just a single kill for the correct faction needs to be made:
    ```
    { "timestamp":"2022-08-06T07:38:08Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"cutter", "Ship_Localised":"Imperial Cutter", "ScanStage":3, "PilotName":"$LUASC_Scenario_Warzone_NPC_WarzoneGeneral_Emp;", "PilotName_Localised":"Imperial Captain", "PilotRank":"Elite", "ShieldHealth":94.610474, "HullHealth":100.000000, "Faction":"Skiraragea Allied PLC" }

    { "timestamp":"2024-02-26T18:12:59Z", "event":"FactionKillBond", "Reward":49496, "AwardingFaction":"The Sovereign Justice Collective", "VictimFaction":"Skiraragea Allied PLC" }
    ```
- [ ] Track side objective Enemy Propagandists: Detect target name, `$LUASC_Scenario_Warzone_NPC_WarzoneCorrespondent` at ScanStage 3, and subsequent `FactionKillBond`. All three kills for the correct faction must be made:
    ```
    { "timestamp":"2024-02-29T17:44:53Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"cutter", "Ship_Localised":"Imperial Cutter", "ScanStage":3, "PilotName":"$LUASC_Scenario_Warzone_NPC_WarzoneCorrespondent;", "PilotName_Localised":"Warzone Correspondent", "PilotRank":"Expert", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Skiraragea Allied PLC", "LegalStatus":"Lawless" }

    { "timestamp":"2024-02-26T18:12:59Z", "event":"FactionKillBond", "Reward":49496, "AwardingFaction":"The Sovereign Justice Collective", "VictimFaction":"Skiraragea Allied PLC" }
   ```
